services:
  - name: jogodavelha
    type: web
    env: node
    region: oregon # Escolha a região mais próxima para você, como oregon, frankfurt, etc.
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_HOST
        value: mysql-aula.cuebxlhckhcy.us-east-1.rds.amazonaws.com
      - key: DB_USER
        value: mysqlaula
      - key: DB_PASSWORD
        value: MySQLAula123!
      - key: DB_NAME
        value: mysqlaula
      - key: DB_PORT
        value: "3306"
